project_id = "ajotwgirccdjntuotxzy"

[functions.send-invitation-emails]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.webhook-dispatcher]
verify_jwt = false

[functions.face-recognition]
verify_jwt = false