// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stovicncahncadyzxxjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0b3ZpY25jYWhuY2FkeXp4eGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTk4MzUsImV4cCI6MjA2MDIzNTgzNX0.EBGKsVHPbwDQ2r8yD5NSINrrTOk-1fzkNQ__kN22n_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);