// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajotwgirccdjntuotxzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqb3R3Z2lyY2Nkam50dW90eHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2Mzc5NDUsImV4cCI6MjA4MzIxMzk0NX0.In3UFmKIIWg0H5dwWRgSjwRAsGLuyP7-oEUMAZRw46U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);