// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahcpeapywabsigkxpsjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoY3BlYXB5d2Fic2lna3hwc2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Njk2NDUsImV4cCI6MjA1OTU0NTY0NX0.0yKqD19Y8tvS4JxBu6yu4AVh8ca6X9pYhpjMlAdsyUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);